"""
VLM-only Agent Pipeline
Only the VLM is used to produce the final solution (no separate LLM step).
Prompt mirrors the LLM-only variant with small wording changes.
"""
import os
import sys
import time
import logging
import json
import numpy as np
from datetime import datetime
from types import SimpleNamespace
from agent_system.environments.env_manager import *
from vlm_agent import VLMAgent
from two_level_agent_pipeline import build_env, create_visualization_image, save_trajectory
import termcolor


def vlm_solution_prompt(observation: str, image_present: bool):
    """Prompt for VLM when VLM is the only solution agent."""
    image_note = " + [Image provided]" if image_present else ""
    prompt = f"""Role: Visual Precision Executor
Input Data: {observation}{image_note}

Task: Based on the visual layout and coordinates, produce a routing solution abiding by the rules below.

Mandatory Rules:
1. Unique Visit: The "route" must include every city index exactly once.
2. Closed Loop: The path is a cycle (last node returns to first). Do not repeat the start node in the list.
3. Calculation: "objective" must be the total Euclidean distance of the entire cycle.
4. No Prose: No CoT, no explanations, no code, no markdown backticks. Output raw JSON only.

Output Format:
{{
  "route": [node_indices],
  "objective": total_distance
}}"""
    return prompt


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--env_name", default=os.environ.get("ENV_NAME", "ml4co-kit"))
    parser.add_argument("--sub_env", default=os.environ.get("SUB_ENV", "tsp"))
    parser.add_argument("--vlm_api_url", default=os.environ.get("VLM_API_URL", "http://localhost:8000/v1"))
    parser.add_argument("--api_key", default=os.environ.get("API_KEY", "token-abc123456"))
    parser.add_argument("--env_num", default=os.environ.get("ENV_NUM", "3"))
    parser.add_argument("--test_times", default=os.environ.get("TEST_TIMES", "1"))
    parser.add_argument("--vlm_model_name", default=os.environ.get("VLM_MODEL_NAME", "vlm"))
    args = parser.parse_args()

    env_name = args.env_name
    sub_env = args.sub_env if args.sub_env is not None else (env_name.split("/", 1)[1] if "/" in env_name else "tsp")
    vlm_api_url = args.vlm_api_url
    api_key = args.api_key
    env_num = int(args.env_num)
    test_times = int(args.test_times)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    log_dir = f"logs/vlm_only/ml4co-kit_{sub_env}"
    trajectory_dir = os.path.join(log_dir, f"trajectories_{timestamp}")
    os.makedirs(log_dir, exist_ok=True)
    os.makedirs(trajectory_dir, exist_ok=True)

    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
    logging.info("VLM-only Agent Pipeline")

    env_manager = build_env(env_name, env_num, sub_env=sub_env)
    logging.info("✓ Environment built")

    vlm_agent = VLMAgent(api_base_url=vlm_api_url, api_key=api_key, model_name=args.vlm_model_name)
    logging.info("✓ VLM Agent initialized")

    all_rewards = []
    all_invalid_actions = []

    for test_idx in range(test_times):
        logging.info(f"Start test {test_idx + 1}/{test_times}")
        start_time = time.time()
        # Count invalid actions this test (reward == -1000)
        test_invalid_actions = 0

        obs, infos = env_manager.reset(kwargs={})
        logging.info(f"Reset completed. Batch size: {len(obs['text'])}")

        actions = []
        trajectories = []

        for i in range(env_num):
            env_obs = obs['text'][i]
            logging.info(f"Env {i} Observation:\n{env_obs[:300]}...")

            trajectory = {'observation': env_obs, 'image_base64': None, 'solution': None}

            image_base64 = None
            try:
                image_base64 = create_visualization_image(env_manager, i, sub_env)
                if image_base64:
                    trajectory['image_base64'] = image_base64
                    logging.info(f"Env {i}: Visualization created")
            except Exception as e:
                logging.warning(f"Visualization failed for env {i}: {e}")

            prompt = vlm_solution_prompt(env_obs, image_base64 is not None)
            try:
                solution = vlm_agent.generate(prompt, image=image_base64, max_tokens=2048, temperature=0.3)
                trajectory['solution'] = solution
                actions.append(solution)
                logging.info(f"Env {i} Solution generated by VLM")
            except Exception as e:
                logging.error(f"VLM generation failed for env {i}: {e}")
                actions.append("[]")
                trajectory['solution'] = "[]"

            trajectories.append(trajectory)

        termcolor.cprint(f"Actions: {[a[:120] + '...' if len(a) > 120 else a for a in actions]}", 'blue')
        obs, rewards, dones, infos = env_manager.step(actions)

        for i in range(env_num):
            reward = float(rewards[i])
            all_rewards.append(reward)
            if i < len(trajectories):
                trajectories[i]['reward'] = reward
                trajectories[i]['env_reward'] = reward
            # 检测无效 action（reward == -1000）
            if reward == -1000:
                test_invalid_actions += 1
            try:
                save_trajectory(trajectory_dir, test_idx, i, trajectories[i])
            except Exception as e:
                logging.warning(f"Failed to save trajectory for env {i}: {e}")

        elapsed_time = time.time() - start_time
        logging.info(f"Test {test_idx + 1} completed in {elapsed_time:.2f}s")
        all_invalid_actions.append(test_invalid_actions)
        logging.info(f"Invalid actions in test {test_idx}: {test_invalid_actions} / {env_num} ({(test_invalid_actions/env_num if env_num>0 else 0):.2%})")

    logging.info(f"Overall Rewards avg ± std: {np.mean(all_rewards):.4f} ± {np.std(all_rewards):.4f}")
    total_invalid = int(np.sum(all_invalid_actions)) if len(all_invalid_actions) > 0 else 0
    logging.info(f"Total invalid actions across all tests: {total_invalid} / {test_times * env_num} ({(total_invalid / (test_times * env_num) if test_times*env_num>0 else 0):.2%})")
    logging.info(f"All trajectories saved to: {trajectory_dir}")


